# Generated by Django 2.0 on 2017-12-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='magnitude',
            field=models.CharField(choices=[('sm', 'Small'), ('md', 'Medium'), ('lg', 'Large')], default='sm', max_length=2),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('ip', 'In Progress'), ('fn', 'Finished'), ('dp', 'Deprecated'), ('uf', 'Unfinished'), ('bb', 'Back Burner'), ('up', 'Upcoming')], default='ip', max_length=2),
        ),
    ]
